name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fix post run npm cleanup
        run: mkdir -p /home/runner/.npm
        continue-on-error: true

      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: 'npm'

      - name: Install dependencies
        run: |
          sudo npm install -g coffeescript@1.12.7

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Extract repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Set zip file env name
        run: echo "ZIP_NAME=${{env.REPOSITORY_NAME}}.zip" >> $GITHUB_ENV

      - name: Build and Package
        shell: bash
        run: make zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: true
          generate_release_notes: true
          files: |
            build/${{ env.ZIP_NAME }}
            README.md